var employeeID = 1;
console.log(employeeID);
var employeeName;
employeeName = "asha";
console.log(employeeName);
console.log("employeeId is type of" + typeof employeeID);
console.log("employeeId is type of" + typeof employeeName);
var isEmployee = true;
console.log("employeeId is type of" + typeof isEmployee);
var nullvalue = null;
console.log("nullvalue is type of" + typeof (nullvalue));
console.log("undefined is type of" + typeof (undefined));
var somevalue = 1;
console.log("any is now" + typeof (somevalue));
var somevalue = "asha";
console.log("any is now" + typeof (somevalue));
var somevalue = true;
console.log("any is now" + typeof (somevalue));
var somevalue = { name: "jany" };
console.log("any is now" + typeof (somevalue));
var somevalue = function () { };
console.log("any is now" + typeof (somevalue));
var somevalue = [1, 2];
console.log("any is now" + typeof (somevalue));
var obj = [];
obj = ["asha", "jany"];
console.log(obj);
var intarrray;
intarrray = [1, 2, 3];
console.log(intarrray);
var mixed = [];
mixed = [1, "asha", 300];
console.log(mixed);
